version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
